<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
<head>
<META http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="version" content="6.0.3">
<link rel="shortcut icon" href="../icons/favicon.ico" type="image/vnd.microsoft.icon">
<title>Exceptions</title>
<link href="man.css" type="text/css" rel="stylesheet">
<meta name="organisation" content="Quality First Software GmbH">
<meta name="copyright" content="(C) 1999-2022 Quality First Software GmbH">
</head>
<body bgcolor="white">
<a name="sec_exceptions"></a>
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="naviheader">
<tr>
<td class="margin"></td><td class="navicon"><a href="manual.html"><img src="../icons/linktop.png" width="34" height="36" border="0" alt="Top" title="Top"></a></td><td class="navicon"><a href="contents.html#table-of-contents"><img src="../icons/linktoc.png" width="34" height="36" border="0" alt="Table of contents" title="Table of contents"></a></td><td class="navicon"><a href="nodes.html#sec_suite"><img src="../icons/linkprev.png" width="34" height="36" border="0" alt="Previous Chapter: 38&nbsp;Elements of a test-suite" title="Previous Chapter: 38&nbsp;Elements of a test-suite"></a></td><td class="navicon"><a href="technical.html#sec_technical"><img src="../icons/linkcont.png" width="34" height="36" border="0" alt="Next Page: IV&nbsp;Technical reference" title="Next Page: IV&nbsp;Technical reference"></a></td><td class="navicon"><img src="../icons/linknextdis.png" width="34" height="36" alt="" border="0"></td><td class="navicon"><a href="reference.html#sec_reference"><img src="../icons/linkup.png" width="34" height="36" border="0" alt="Chapter Overview: III&nbsp;Reference manual" title="Chapter Overview: III&nbsp;Reference manual"></a></td><td class="navicon"><a href="../../manual_en.pdf" target="_parent"><img src="../icons/linkpdf.png" width="34" height="36" border="0" alt="PDF version" title="PDF version"></a></td><td class="homeicon"><a href="http://www.qfs.de/en/qftest/index.html" target="_parent"><img src="../icons/qftest.png" width="127" height="42" border="0" alt="QF-Test" title="QF-Test"></a></td>
</tr>
</table>
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="naviversion">
<tr>
<td>Version 6.0.3</td>
</tr>
</table>
    
<h3 class="header-container h3">
<div>
<span class="numtitle"><a href="contents.html#toc_sec_exceptions">39</a></span>
</div>
<a href="contents.html#toc_sec_exceptions">Exceptions</a>
</h3>
    
<p>
      There are quite a lot of exceptions that can be thrown during the
      execution of a test. This chapter lists the exceptions in hierarchical
      order, shows the typical error messages and gives a short explanation.
    </p>
    
<p>If you want to work with those exceptions in scripts, please take a
      look into <a href="tech_scripting.html#sec_api_exceptions">section 46.8</a>.
    </p>
    
<dl class="exception">
      

      
<a name="ex_TestException"></a>
<dt>
          
<a name="idx_N153733"></a><code>TestException</code>
        
</dt>
<dd>
          
<p>
            This is the base class of all exceptions that can be thrown during
            a test run. The actual exception thrown should almost always be of a derived class. A
            <a href="control.html#step_CatchSequence" shape="rect">'Catch'</a> with the <a href="control.html#att_CatchSequence_exception" shape="rect">'Exception class'</a> set to
            <code>TestException</code> will catch all possible exceptions. Just like in
            Java you should normally not use such a <a href="control.html#step_CatchSequence" shape="rect">'Catch'</a>
            since it may hide unexpected Exceptions.
          </p>
        
</dd>

      

      

      
<a name="ex_ComponentNotFoundException"></a>
<dt>
          
<a name="idx_N153776"></a><code>ComponentNotFoundException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown whenever the target component for an <a href="events.html#sec_events" shape="rect">event</a> or a <a href="checks.html#sec_checks" shape="rect">check</a>
            cannot be determined. Failure of a <a href="miscnodes.html#step_ComponentWaiter" shape="rect">'Wait for component to appear'</a> will also
            cause a <code>ComponentNotFoundException</code> unless the node's
            <a href="miscnodes.html#att_ComponentWaiter_absence" shape="rect">'Wait for absence'</a> attribute is set.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          The target component could not be determined.
        </p>
</dd>

      
      

      
<a name="ex_ScopeNotFoundException"></a>
<dt>
          
<a name="idx_N153833"></a><code>ScopeNotFoundException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown whenever the target component of an explicit scope for an <a href="events.html#sec_events" shape="rect">event</a> or a <a href="checks.html#sec_checks" shape="rect">check</a>
            cannot be determined. Failure of a <a href="miscnodes.html#step_ComponentWaiter" shape="rect">'Wait for component to appear'</a> with an explicit scope will also
            cause a <code>ComponentNotFoundException</code> unless the node's
            <a href="miscnodes.html#att_ComponentWaiter_absence" shape="rect">'Wait for absence'</a> attribute is set.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_ComponentNotFoundException" shape="rect"><code>ComponentNotFoundException</code></a>
</p>
<p>
<b>Message: </b>
          The target component for an explicit scope could not be determined.
          This can be caused by a number of quite	different reasons.
          Please see chapter 5 of the manual for background information and how to proceed.
        </p>
</dd>

      
      

      
<a name="ex_DocumentNotLoadedException"></a>
<dt>
          
<a name="idx_N153890"></a><code>DocumentNotLoadedException</code>
        
</dt>
<dd>
          
<p>
            This exception is a variant of <code>ComponentNotFoundException</code> and thrown
            specifically if a <a href="miscnodes.html#step_DocumentWaiter" shape="rect">'Wait for document to load'</a> node fails.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_ComponentNotFoundException" shape="rect"><code>ComponentNotFoundException</code></a>
</p>
<p>
<b>Message: </b>
          The target document was not loaded (anew).
        </p>
</dd>

      
      

      
<a name="ex_PageNotFoundException"></a>
<dt>
          
<a name="idx_N153931"></a><code>PageNotFoundException</code>
        
</dt>
<dd>
          
<p>
            This exception is a variant of a <code>ComponentNotFoundException</code> and thrown
            specifically if a <a href="events.html#step_SelectionEventStep" shape="rect">'Selection'</a> node fails to select a desired
            page in a PDF-Document.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_ComponentNotFoundException" shape="rect"><code>ComponentNotFoundException</code></a>
</p>
<p>
<b>Message: </b>
            The target page "pagename" could not be determined.
        </p>
</dd>

      
      

      
<a name="ex_ComponentFoundException"></a>
<dt>
          
<a name="idx_N153972"></a><code>ComponentFoundException</code>
        
</dt>
<dd>
          
<p>
            This is the opposite of a <code>ComponentNotFoundException</code>, thrown
            by a <a href="miscnodes.html#step_ComponentWaiter" shape="rect">'Wait for component to appear'</a> with the <a href="miscnodes.html#att_ComponentWaiter_absence" shape="rect">'Wait for absence'</a>
            attribute set.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          The target component does exist.
        </p>
</dd>

      
      

      
<a name="ex_ModalDialogException"></a>
<dt>
          
<a name="idx_N154019"></a><code>ModalDialogException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when an <a href="events.html#sec_events" shape="rect">event</a>
            is blocked by a modal dialog. See the option <a href="opt_play.html#opt_checkmodaldialog" shape="rect">Check for modal dialogs</a> for
            details.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          A modal dialog blocked this event. (plus information about the
          dialog)
        </p>
</dd>

      
      

      
<a name="ex_ComponentCannotGetFocusException"></a>
<dt>
          
<a name="idx_N154061"></a><code>ComponentCannotGetFocusException</code>
        
</dt>
<dd>
          
<p>
            
<span class="margin"><span class="note">Note</span></span> This exception is obsolete and should not
            occur anymore.
          </p>
          
<p>
            This exception is thrown when the target component for a
            <a href="events.html#step_KeyEventStep" shape="rect">'Key event'</a> or <a href="events.html#step_TextInputStep" shape="rect">'Text input'</a> is a text component that
            cannot get the keyboard focus for some reason. With JDK&nbsp;1.4 the
            event cannot be delivered to the component in that case.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          The target component cannot get the keyboard focus.
        </p>
</dd>

      
      

      
<a name="ex_DisabledComponentException"></a>
<dt>
          
<a name="idx_N154110"></a><code>DisabledComponentException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when the target component for a
            <a href="events.html#step_MouseEventStep" shape="rect">'Mouse event'</a>, <a href="events.html#step_KeyEventStep" shape="rect">'Key event'</a> or <a href="events.html#step_TextInputStep" shape="rect">'Text input'</a> is
            not enabled. In that case the event would be silently ignored,
            very likely leading to unexpected results during further execution
            of the test.
          </p>
          
<p>
            For backwards compatibility this kind of exception can be
            suppressed by deactivating the option <a href="opt_play.html#opt_throwdisabled">Throw DisabledComponentException</a>.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          The target component is disabled and cannot receive events.
        </p>
</dd>

      
      

      
<a name="ex_DisabledComponentStepException"></a>
<dt>
          
<a name="idx_N154166"></a><code>DisabledComponentStepException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when the target component for a
            <a href="events.html#step_MouseEventStep" shape="rect">'Mouse event'</a>, <a href="events.html#step_KeyEventStep" shape="rect">'Key event'</a> or <a href="events.html#step_TextInputStep" shape="rect">'Text input'</a> is
            disabled under 'Windows and components'.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          The target component is disabled under 'Windows and components', so it cannot
          receive events.
        </p>
</dd>

      
      

      
<a name="ex_BadItemException"></a>
<dt>
          
<a name="idx_N154222"></a><code>BadItemException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown by ItemResolvers if element and item types do not match.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
</dd>

      
      

      
<a name="ex_ExecutionTimeoutExpiredException"></a>
<dt>
          
<a name="idx_N154251"></a><code>ExecutionTimeoutExpiredException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when the execution timeout of a node has been exceeded.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          Execution timeout of ... ms expired.
        </p>
</dd>

      
      

      
<a name="ex_BusyPaneException"></a>
<dt>
          
<a name="idx_N154283"></a><code>BusyPaneException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when the target component for a
            <a href="events.html#step_MouseEventStep" shape="rect">'Mouse event'</a>, <a href="events.html#step_KeyEventStep" shape="rect">'Key event'</a> or <a href="events.html#step_TextInputStep" shape="rect">'Text input'</a> is
            covered by a GlassPane with a "busy" mouse cursor. The option
            <a href="opt_play.html#opt_waitforbusy">Wait for 'busy' GlassPane (ms)</a> determines how long QF-Test will wait for the GlassPane
            to disappear before the exception is actually triggered.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          The target component is covered by a 'busy' GlassPane.
        </p>
</dd>

      
      

      
<a name="ex_InvisibleDnDTargetException"></a>
<dt>
          
<a name="idx_N154336"></a><code>InvisibleDnDTargetException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when the location in the target component for a
            <a href="events.html#step_MouseEventStep" shape="rect">'Mouse event'</a> of type <code>DRAG_FROM</code>, <code>DRAG_OVER</code> or
            <code>DROP_TO</code> for a Drag&amp;Drop operation is invisible and cannot be made visible by
            scrolling the target component.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          The target location for the Drag&amp;Drop operation could not be made visible.
        </p>
</dd>

      
      

      
<a name="ex_InvisibleTargetComponentException"></a>
<dt>
          
<a name="idx_N154383"></a><code>InvisibleTargetComponentException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when the target component is invisible.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_ComponentNotFoundException" shape="rect"><code>ComponentNotFoundException</code></a>
</p>
<p>
<b>Message: </b>
          The target component is invisible.
        </p>
</dd>

      
      

      
<a name="ex_InvisibleTargetItemException"></a>
<dt>
          
<a name="idx_N154415"></a><code>InvisibleTargetItemException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown if the surrounding target component is visible, but the target element in it is invisible.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_IndexNotFoundException" shape="rect"><code>IndexNotFoundException</code></a>
</p>
<p>
<b>Message: </b>
          The target item for index '...' is invisible.
        </p>
</dd>

      
      

      
<a name="ex_DeadlockTimeoutException"></a>
<dt>
          
<a name="idx_N154447"></a><code>DeadlockTimeoutException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when the SUT does not react for a given
            amount of time which is defined in the option <a href="opt_play.html#opt_deadlocktimeout">Deadlock detection (s)</a>.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          The previous operation timed out. It is very likely that the client
          '...' went into a deadlock.
        </p>
</dd>

      
      

      
<a name="ex_DownloadNotCompleteException"></a>
<dt>
          
<a name="idx_N154482"></a><code>DownloadNotCompleteException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown, when waiting for a download that is not complete.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_ComponentNotFoundException" shape="rect"><code>ComponentNotFoundException</code></a>
</p>
<p>
<b>Message: </b>
          The download of the file '...' has not completed yet.
        </p>
</dd>

      
      

      
<a name="ex_DownloadStillActiveException"></a>
<dt>
          
<a name="idx_N154514"></a><code>DownloadStillActiveException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown, when trying to download to a file
            that is still blocked by another download.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_ComponentNotFoundException" shape="rect"><code>ComponentNotFoundException</code></a>
</p>
<p>
<b>Message: </b>
          The download of the file '...' is still active and you cannot start
          another download for the same file.
        </p>
</dd>

      
      

      
<a name="ex_NoSuchDownloadException"></a>
<dt>
          
<a name="idx_N154546"></a><code>NoSuchDownloadException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown, when waiting for a download that was never started.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_ComponentNotFoundException" shape="rect"><code>ComponentNotFoundException</code></a>
</p>
<p>
<b>Message: </b>
          There was attempt to download the file '...'.
        </p>
</dd>

      

      

      
<a name="ex_VariableException"></a>
<dt>
          
<a name="idx_N154578"></a><code>VariableException</code>
        
</dt>
<dd>
          
<p>
            This exception is never thrown itself but is the base class for
            exceptions thrown in the context of variable expansion.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
</dd>

      
      

      
<a name="ex_BadVariableSyntaxException"></a>
<dt>
          
<a name="idx_N154607"></a><code>BadVariableSyntaxException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when a value that is to be expanded
            doesn't follow a proper variable syntax (e.g. no closing brace).
          </p>
        
<p>
<b>Base class: </b><a href="#ex_VariableException" shape="rect"><code>VariableException</code></a>
</p>
<p>
<b>Message: </b>
          Invalid variable syntax: '...'
        </p>
</dd>

      
      

      
<a name="ex_MissingPropertiesException"></a>
<dt>
          
<a name="idx_N154639"></a><code>MissingPropertiesException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when no properties or ResourceBundle are
            available for the group name  of a property or resource looked up with
            ${group:prop} (see <a href="miscnodes.html#step_LoadResourcesStep" shape="rect">'Load resources'</a> and
            <a href="miscnodes.html#step_LoadPropertiesStep" shape="rect">'Load properties'</a>).
          </p>
        
<p>
<b>Base class: </b><a href="#ex_VariableException" shape="rect"><code>VariableException</code></a>
</p>
<p>
<b>Message: </b>
          No properties or resources are available under the name '...'.
        </p>
</dd>

      
      

      
<a name="ex_MissingPropertyException"></a>
<dt>
          
<a name="idx_N154683"></a><code>MissingPropertyException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when a property looked up with
            ${id:property} is not available (see <a href="miscnodes.html#step_LoadResourcesStep" shape="rect">'Load resources'</a> and
            <a href="miscnodes.html#step_LoadPropertiesStep" shape="rect">'Load properties'</a>).
          </p>
        
<p>
<b>Base class: </b><a href="#ex_VariableException" shape="rect"><code>VariableException</code></a>
</p>
<p>
<b>Message: </b>
          There is no property or resource named '...'.
        </p>
</dd>

      
      

      
<a name="ex_RecursiveVariableException"></a>
<dt>
          
<a name="idx_N154727"></a><code>RecursiveVariableException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when the expansion of a variable
            expression leads to recursive variable lookup, e.g. if you set the
            variable named <code>x</code> to <code>$(y)</code> and the
            variable named <code>y</code> to <code>$(x)</code> and then try to
            expand the value <code>$(x)</code>.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_VariableException" shape="rect"><code>VariableException</code></a>
</p>
<p>
<b>Message: </b>
          The variable '...' could not be expanded since it lead to recursive
          lookup.
        </p>
</dd>

      
      

      
<a name="ex_UnboundVariableException"></a>
<dt>
          
<a name="idx_N154774"></a><code>UnboundVariableException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when a variable for a value that is to be
            expanded doesn't exist.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_VariableException" shape="rect"><code>VariableException</code></a>
</p>
<p>
<b>Message: </b>
          The variable '...' is not bound.
        </p>
</dd>

      
      

      
<a name="ex_VariableNumberException"></a>
<dt>
          
<a name="idx_N154806"></a><code>VariableNumberException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when a variable expansion for a numeric
            attributes results in something other than a number.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_VariableException" shape="rect"><code>VariableException</code></a>
</p>
<p>
<b>Message: </b>
          The value '...' is not a valid number.
        </p>
</dd>

      

      

      
<a name="ex_BadExpressionException"></a>
<dt>
          
<a name="idx_N154838"></a><code>BadExpressionException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when evaluating a $[...] expression fails
            (see <a href="user_variables.html#usec_expressions">section 6.6</a>).
          </p>
        
<p>
<b>Base class: </b><a href="#ex_ScriptException" shape="rect"><code>ScriptException</code></a>
</p>
<p>
<b>Message: </b>
          The expression '...' is invalid.
        </p>
</dd>

      
      

      
<a name="ex_BadTestException"></a>
<dt>
          
<a name="idx_N154873"></a><code>BadTestException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when evaluating the <a href="control.html#att_IfSequence_test" shape="rect">'Condition'</a>
            of an <a href="control.html#step_IfSequence" shape="rect">'If'</a> or <a href="control.html#step_ElseifSequence" shape="rect">'Elseif'</a> node fails.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_ScriptException" shape="rect"><code>ScriptException</code></a>
</p>
<p>
<b>Message: </b>
          The expression '...' is not a valid test.
        </p>
</dd>

      
      

      
<a name="ex_BadRegexpException"></a>
<dt>
          
<a name="idx_N154923"></a><code>BadRegexpException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown whenever converting a String to a regular
            expression (see <a href="tech_regexp.html#sec_regexp">section 45.3</a>) fails, e.g. for
            <a href="components.html#step_SubItemStep" shape="rect">'Item'</a> or <a href="checks.html#step_CheckStringStep" shape="rect">'Check text'</a> nodes.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          The value '...' is not a valid regular expression.
        </p>
</dd>

      
      

      
<a name="ex_BadRangeException"></a>
<dt>
          
<a name="idx_N154970"></a><code>BadRangeException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when the syntax of the 'Iteration ranges' for a 'Data binder' node
            has invalid syntax or specifies an index outside the valid data range.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          Invalid iteration range syntax: '...'.<br>
          Invalid iteration range index: '...'.
        </p>
</dd>

      

      

      
<a name="ex_CannotExecuteException"></a>
<dt>
          
<a name="idx_N155010"></a><code>CannotExecuteException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when execution of a process from a
            <a href="processes.html#step_SUTClientStarter" shape="rect">'Start SUT client'</a>, <a href="processes.html#step_JavaClientStarter" shape="rect">'Start Java SUT client'</a> or
            <a href="processes.html#step_ProcessClientStarter" shape="rect">'Start process'</a> node fails.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          An error occurred while starting process '...'. Please check the
          process and PATH settings.
        </p>
</dd>

      
      

      
<a name="ex_InvalidDirectoryException"></a>
<dt>
          
<a name="idx_N155060"></a><code>InvalidDirectoryException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when the <a href="processes.html#att_SUTClientStarter_directory" shape="rect">'Directory'</a>
            attribute of a <a href="processes.html#step_SUTClientStarter" shape="rect">'Start SUT client'</a> node refers to a
            non-existent directory.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          The directory '...' doesn't exist.
        </p>
</dd>

      

      

      
<a name="ex_CheckFailedException"></a>
<dt>
          
<a name="idx_N155104"></a><code>CheckFailedException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when a <a href="checks.html#sec_checks" shape="rect">check</a>
            node with activated <a href="checks.html#att_CheckStringStep_raise" shape="rect">'Throw exception on failure'</a> attribute fails.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          The check for client '...' failed. Expected: '...'. Got: '...'.
        </p>
</dd>

      
      

      
<a name="ex_CheckNotSupportedException"></a>
<dt>
          
<a name="idx_N155147"></a><code>CheckNotSupportedException</code>
        
</dt>
<dd>
          
<p>
            As explained in the section about <a href="checks.html#sec_checks" shape="rect">checks</a>, each check can handle only a
            limited set of target components. This exception is thrown when
            the target component is not suitable for a check.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          This kind of check is not possible for a component of class '...'.
        </p>
</dd>

      
      

      
<a name="ex_OperationNotSupportedException"></a>
<dt>
          
<a name="idx_N155184"></a><code>OperationNotSupportedException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when an operation like
            <a href="queries.html#step_FetchTextStep" shape="rect">'Fetch text'</a> is not supported for the designated target
            component.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          This operation is not possible for a component of class '...'.
        </p>
</dd>

      
      

      
<a name="ex_BadComponentException"></a>
<dt>
          
<a name="idx_N155222"></a><code>BadComponentException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown, when a component for an <a href="events.html#sec_events" shape="rect">event</a> is not suitable, i.e. a non-window
            for a <a href="events.html#step_WindowEventStep" shape="rect">'Window event'</a>.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          The component of class '...' is not a window.
        </p>
</dd>

      

      

      
<a name="ex_IndexFormatException"></a>
<dt>
          
<a name="idx_N155265"></a><code>IndexFormatException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when an invalid index format for a
            sub-item is encountered (see <a href="user_subitems.html#sec_directsubitemeasy">subsection 5.9.1</a>).
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          The value '...' is not a valid string index/number/regexp.
        </p>
</dd>

      
      

      
<a name="ex_IndexFoundException"></a>
<dt>
          
<a name="idx_N155300"></a><code>IndexFoundException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when a sub-item is found during execution of a
            <a href="miscnodes.html#step_ComponentWaiter" shape="rect">'Wait for component to appear'</a> node that looks for the absence of the item.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_ComponentFoundException" shape="rect"><code>ComponentFoundException</code></a>
</p>
<p>
<b>Message: </b>
          The item for index '...' was found.
        </p>
</dd>

      
      

      
<a name="ex_IndexNotFoundException"></a>
<dt>
          
<a name="idx_N155338"></a><code>IndexNotFoundException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when no sub-item can be located for a
            given index.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_ComponentNotFoundException" shape="rect"><code>ComponentNotFoundException</code></a>
</p>
<p>
<b>Message: </b>
          No item was found for index '...'.
        </p>
</dd>

      
      

      
<a name="ex_IndexRequiredException"></a>
<dt>
          
<a name="idx_N155370"></a><code>IndexRequiredException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when no sub-item index is provided for an
            operation that requires one, e.g. a <a href="checks.html#step_CheckStringStep" shape="rect">'Check text'</a> on a
            <code>JTree</code>.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          This operation requires an index.
        </p>
</dd>

      
      

      
<a name="ex_UnexpectedIndexException"></a>
<dt>
          
<a name="idx_N155411"></a><code>UnexpectedIndexException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when a sub-item index is provided for an
            operation that does not require one, e.g. a <a href="checks.html#step_CheckItemsStep" shape="rect">'Check items'</a>
            on a <code>JTree</code>.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          This operation doesn't support an index for a component of class
          '...'.
        </p>
</dd>

      

      

      
<a name="ex_ClientNotConnectedException"></a>
<dt>
          
<a name="idx_N155452"></a><code>ClientNotConnectedException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when the target client for an operation
            is not connected. It differs from a <a href="#ex_NoSuchClientException" shape="rect"><code>NoSuchClientException</code></a> in
            that there is an active process for that name but no RMI
            connection.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          Client '...' is not connected.
        </p>
</dd>

      
      

      
<a name="ex_CannotAttachException"></a>
<dt>
          
<a name="idx_N155490"></a><code>CannotAttachException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when attaching to a Windows application failed.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          An error occurred while attaching to application '... title: ...'.
        </p>
</dd>

      
      

      
<a name="ex_ConnectionFailureException"></a>
<dt>
          
<a name="idx_N155522"></a><code>ConnectionFailureException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when the connection to a client failed.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          The connection to client '...' failed.
        </p>
</dd>

      
      

      
<a name="ex_NoSuchClientException"></a>
<dt>
          
<a name="idx_N155554"></a><code>NoSuchClientException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when the target client for an operation
            does not exist.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          Client '...' doesn't exist.
        </p>
</dd>

      
      

      
<a name="ex_NoSuchEngineException"></a>
<dt>
          
<a name="idx_N155586"></a><code>NoSuchEngineException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when an engine is referenced
            that does not exist or when an attempt is made to use an
            engine that has not (yet) been connected to QF-Test.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          There is no engine named '...' in client '...'.
        </p>
</dd>

      
      

      
<a name="ex_DuplicateClientException"></a>
<dt>
          
<a name="idx_N155618"></a><code>DuplicateClientException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown if an attempt is made to run more than
            one client simultaneously under the same name.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          A client named '...' has already been started.
        </p>
</dd>

      
      

      
<a name="ex_UnexpectedClientException"></a>
<dt>
          
<a name="idx_N155650"></a><code>UnexpectedClientException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when an unexpected exception is thrown in
            the SUT during the replay of an <a href="events.html#sec_events" shape="rect">event</a>.
            Unless it is due to a bug in QF-Test, it indicates a problem in
            the SUT.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          Unexpected exception in client '...'.
        </p>
</dd>

      
      

      
<a name="ex_ExtensionException"></a>
<dt>
          
<a name="idx_N155687"></a><code>ExtensionException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when a client throws an unexpected exception.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          Exception in external code: ...
        </p>
</dd>

      
      

      
<a name="ex_ClientNotTerminatedException"></a>
<dt>
          
<a name="idx_N155719"></a><code>ClientNotTerminatedException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when a <a href="processes.html#step_ProcessWaiter" shape="rect">'Wait for process to terminate'</a> node is
            executed and the process doesn't terminate.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          The process '...' did not terminate.
        </p>
</dd>

      
      

      
<a name="ex_UnexpectedExitCodeException"></a>
<dt>
          
<a name="idx_N155757"></a><code>UnexpectedExitCodeException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when the exit code of a terminated client
            doesn't match the expected value in a <a href="processes.html#step_ProcessWaiter" shape="rect">'Wait for process to terminate'</a> node's
            <a href="processes.html#att_ProcessWaiter_check" shape="rect">'Expected exit code'</a> attribute.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          Exit code mismatch.
        </p>
</dd>

      
      

      
<a name="ex_BadExitCodeException"></a>
<dt>
          
<a name="idx_N155801"></a><code>BadExitCodeException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when the <a href="processes.html#att_ProcessWaiter_check" shape="rect">'Expected exit code'</a>
            attribute of a <a href="processes.html#step_ProcessWaiter" shape="rect">'Wait for process to terminate'</a> node doesn't match the
            specification and cannot be parsed.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          Illegal exit code '...'. Please use '==', '!=', '&lt;' or '&gt;'
          followed by a number.
        </p>
</dd>

      

      

      
<a name="ex_ComponentIdMismatchException"></a>
<dt>
          
<a name="idx_N155845"></a><code>ComponentIdMismatchException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when the <a href="events.html#att_MouseEventStep_component" shape="rect">'QF-Test component ID'</a>
            attribute of a node points to a node that is not a
            <a href="components.html#step_WindowStep" shape="rect">'Window'</a>, <a href="components.html#step_ComponentStep" shape="rect">'Component'</a> or <a href="components.html#step_SubItemStep" shape="rect">'Item'</a>.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          The node '...' with the QF-Test ID '...' is not a component.
        </p>
</dd>

      
      

      
<a name="ex_UnresolvedComponentIdException"></a>
<dt>
          
<a name="idx_N155901"></a><code>UnresolvedComponentIdException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when the target of the
            <a href="events.html#att_MouseEventStep_component" shape="rect">'QF-Test component ID'</a> attribute of a node cannot be
            determined.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          There is no node with the QF-Test ID '...'.
        </p>
</dd>

      

      

      
<a name="ex_TestNotFoundException"></a>
<dt>
          
<a name="idx_N155939"></a><code>TestNotFoundException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when the <a href="sequences.html#step_TestCase" shape="rect">'Test-case'</a> or <a href="sequences.html#step_TestSet" shape="rect">'Test-set'</a> for a
            <a href="sequences.html#step_TestCall" shape="rect">'Test call'</a> cannot be determined.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          The test '...' does not exist.
        </p>
</dd>

      
      

      
<a name="ex_DependencyNotFoundException"></a>
<dt>
          
<a name="idx_N155989"></a><code>DependencyNotFoundException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when the <a href="dependencies.html#step_Dependency" shape="rect">'Dependency'</a> for a
            <a href="dependencies.html#step_DependencyReference" shape="rect">'Dependency reference'</a> cannot be determined.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          The dependency '...' does not exist.
        </p>
</dd>

      
      

      
<a name="ex_InconsistentDependenciesException"></a>
<dt>
          
<a name="idx_N156033"></a><code>InconsistentDependenciesException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when the <a href="dependencies.html#step_Dependency" shape="rect">'Dependency'</a>
            cannot be linearized due to inconsistent references.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          The <a href="dependencies.html#step_Dependency" shape="rect">'Dependency'</a> cannot be linearized due to inconsistent references.
        </p>
</dd>

      
      

      
<a name="ex_RecursiveDependencyReferenceException"></a>
<dt>
          
<a name="idx_N156077"></a><code>RecursiveDependencyReferenceException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when the <a href="dependencies.html#step_Dependency" shape="rect">'Dependency'</a>
            cannot be linearized due to recursive references.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          The <a href="dependencies.html#step_Dependency" shape="rect">'Dependency'</a> cannot be linearized due to recursive references.
        </p>
</dd>

      

      

      
<a name="ex_ProcedureNotFoundException"></a>
<dt>
          
<a name="idx_N156121"></a><code>ProcedureNotFoundException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when the <a href="procedures.html#step_Procedure" shape="rect">'Procedure'</a> for a
            <a href="procedures.html#step_ProcedureCall" shape="rect">'Procedure call'</a> cannot be determined.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          The procedure '...' does not exist.
        </p>
</dd>

      
      

      
<a name="ex_StackOverflowException"></a>
<dt>
          
<a name="idx_N156165"></a><code>StackOverflowException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when the nesting of <a href="procedures.html#step_ProcedureCall" shape="rect">'Procedure calls'</a>
            gets too deep, hinting to a problem with endless recursion. See
            also the option <a href="opt_play.html#opt_callstacksize" shape="rect">Call stack size</a>.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          Too many nested procedure calls.
        </p>
</dd>

      

      

      
<a name="ex_UserException"></a>
<dt>
          
<a name="idx_N156208"></a><code>UserException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown explicitly by a <a href="control.html#step_ThrowStep" shape="rect">'Throw'</a> node.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          The <a href="control.html#att_ThrowStep_throwmessage" shape="rect">'Exception message'</a> of the <a href="control.html#step_ThrowStep" shape="rect">'Throw'</a> node.
        </p>
</dd>

      
      

      
<a name="ex_CannotRethrowException"></a>
<dt>
          
<a name="idx_N156258"></a><code>CannotRethrowException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when an attempt is made to rethrow an
            exception with a <a href="control.html#step_RethrowStep" shape="rect">'Rethrow'</a> node but no exception
            was caught by a  <a href="control.html#step_CatchSequence" shape="rect">'Catch'</a> node.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          Rethrowing a caught exception can be done only from inside a Catch
          node.
        </p>
</dd>

      
      

      
<a name="ex_ScriptException"></a>
<dt>
          
<a name="idx_N156302"></a><code>ScriptException</code>
        
</dt>
<dd>
          
<p>
            This exception is thrown when the execution of a script
            from a <a href="control.html#step_ServerScriptStep" shape="rect">'Server script'</a> or <a href="control.html#step_ClientScriptStep" shape="rect">'SUT script'</a>
            fails.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          The script failed with the following message:...
        </p>
</dd>

      

      

      
        
<a name="ex_AndroidSdkException"></a>
<dt>
            
<a name="idx_N156346"></a><code>AndroidSdkException</code>
          
</dt>
<dd>
            
<p>
              This is a base class. In order to test Android Applications,
              a valid Android SDK needs to be installed. In case QF-Test detects
              any problem with the Android SDK, an exception derived from this
              base class will be thrown.
            </p>
          
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
</dd>
      

      
      

      
        
<a name="ex_InvalidAndroidSdkPathException"></a>
<dt>
            
<a name="idx_N156375"></a><code>InvalidAndroidSdkPathException</code>
          
</dt>
<dd>
            
<p>
              This exception will be thrown if the specified path does not point
              to a valid Android SDK installation.
            </p>
          
<p>
<b>Base class: </b><a href="#ex_AndroidSdkException" shape="rect"><code>AndroidSdkException</code></a>
</p>
</dd>
      

      
      

      
        
<a name="ex_AndroidSdkNotFoundException"></a>
<dt>
            
<a name="idx_N156404"></a><code>AndroidSdkNotFoundException</code>
          
</dt>
<dd>
            
<p>
              This exception will be thrown in case when QF-Test is unable to determine
              the Android SDK location.
            </p>
          
<p>
<b>Base class: </b><a href="#ex_AndroidSdkException" shape="rect"><code>AndroidSdkException</code></a>
</p>
</dd>
      

      
      

      
        
<a name="ex_InvalidAndroidAdbPathException"></a>
<dt>
            
<a name="idx_N156433"></a><code>InvalidAndroidAdbPathException</code>
          
</dt>
<dd>
            
<p>
              This exception will be thrown in case a given ADB class path is invalid.
            </p>
          
<p>
<b>Base class: </b><a href="#ex_AndroidSdkException" shape="rect"><code>AndroidSdkException</code></a>
</p>
<p>
<b>Message: </b>
            ... is not a valid ADB path. (Source: ..., Reason: ...)
          </p>
</dd>
      

      
      

      
        
<a name="ex_AndroidAdbNotFoundException"></a>
<dt>
            
<a name="idx_N156465"></a><code>AndroidAdbNotFoundException</code>
          
</dt>
<dd>
            
<p>
              This exception will be thrown when no Android Adb was found on the computer.
            </p>
          
<p>
<b>Base class: </b><a href="#ex_AndroidSdkException" shape="rect"><code>AndroidSdkException</code></a>
</p>
<p>
<b>Message: </b>
            No Android ADB was found.
          </p>
</dd>
      

      
      

      
        
<a name="ex_InvalidAndroidEmulatorPathException"></a>
<dt>
            
<a name="idx_N156497"></a><code>InvalidAndroidEmulatorPathException</code>
          
</dt>
<dd>
            
<p>
              This exception will be thrown in case a given Android emulator path is invalid.
            </p>
          
<p>
<b>Base class: </b><a href="#ex_AndroidSdkException" shape="rect"><code>AndroidSdkException</code></a>
</p>
<p>
<b>Message: </b>
            ... is not a valid emulator path. (Source: ..., Reason: ...)
          </p>
</dd>
      

      
      

      
        
<a name="ex_AndroidEmulatorNotFoundException"></a>
<dt>
            
<a name="idx_N156529"></a><code>AndroidEmulatorNotFoundException</code>
          
</dt>
<dd>
            
<p>
              This exception will be thrown when no Android emulator was found on the computer.
            </p>
          
<p>
<b>Base class: </b><a href="#ex_AndroidSdkException" shape="rect"><code>AndroidSdkException</code></a>
</p>
<p>
<b>Message: </b>
            No Android emulator was found.
          </p>
</dd>
      

      
      

      
        
<a name="ex_AndroidVirtualDeviceException"></a>
<dt>
            
<a name="idx_N156561"></a><code>AndroidVirtualDeviceException</code>
          
</dt>
<dd>
            
<p>
              This is a base class. In order to test Android Applications,
              a valid android emulator needs to be installed. The emulator can then run
              an android virtual device (AVD). If QF-Test is not able to find the android
              virtual device or if testing this device is not supported, an exception
              derived from this base class will be thrown.
            </p>
          
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
</dd>
      

      
      

      
        
<a name="ex_NoAndroidVirtualDeviceException"></a>
<dt>
            
<a name="idx_N156590"></a><code>NoAndroidVirtualDeviceException</code>
          
</dt>
<dd>
            
<p>
              An exception of this type will be thrown if no avd was found on which the
              tests may get executed.
            </p>
          
<p>
<b>Base class: </b><a href="#ex_AndroidVirtualDeviceException" shape="rect"><code>AndroidVirtualDeviceException</code></a>
</p>
</dd>
      

      
      

      
        
<a name="ex_NoSupportedAndroidVirtualDeviceException"></a>
<dt>
            
<a name="idx_N156619"></a><code>NoSupportedAndroidVirtualDeviceException</code>
          
</dt>
<dd>
            
<p>
              An exception of this type will be thrown if no supported avd was found on which
              the tests may get executed.
            </p>
          
<p>
<b>Base class: </b><a href="#ex_AndroidVirtualDeviceException" shape="rect"><code>AndroidVirtualDeviceException</code></a>
</p>
</dd>
      

      
      

      
        
<a name="ex_AndroidVirtualDeviceNotFoundException"></a>
<dt>
            
<a name="idx_N156648"></a><code>AndroidVirtualDeviceNotFoundException</code>
          
</dt>
<dd>
            
<p>
              An exception of this type will be thrown if QF-Test was unable to find the
              specified avd.
            </p>
          
<p>
<b>Base class: </b><a href="#ex_AndroidVirtualDeviceException" shape="rect"><code>AndroidVirtualDeviceException</code></a>
</p>
</dd>
      

      
      

      
        
<a name="ex_AndroidVirtualDeviceNotSupportedException"></a>
<dt>
            
<a name="idx_N156677"></a><code>AndroidVirtualDeviceNotSupportedException</code>
          
</dt>
<dd>
            
<p>
              An exception of this type will be thrown if QF-Test is not able to test the
              specified avd.
            </p>
          
<p>
<b>Base class: </b><a href="#ex_AndroidVirtualDeviceException" shape="rect"><code>AndroidVirtualDeviceException</code></a>
</p>
</dd>
      

      
      

      
        
<a name="ex_AndroidVirtualDeviceParsingException"></a>
<dt>
            
<a name="idx_N156706"></a><code>AndroidVirtualDeviceParsingException</code>
          
</dt>
<dd>
            
<p>
              An exception of this type will be thrown if QF-Test fails to parse the string
              specifying the android emulator to use.
            </p>
          
<p>
<b>Base class: </b><a href="#ex_AndroidVirtualDeviceException" shape="rect"><code>AndroidVirtualDeviceException</code></a>
</p>
</dd>
      

      

      

      
<a name="ex_BreakException"></a>
<dt>
          
<a name="idx_N156735"></a><code>BreakException</code>
        
</dt>
<dd>
          
<p>
            This is not a standard TestException and cannot be caught by a <a href="control.html#step_CatchSequence" shape="rect">'Catch'</a>
            node. It is thrown by a <a href="control.html#step_BreakStep" shape="rect">'Break'</a> node in order to break out of a loop. From a
            script, raising a <code>BreakException</code> will have the same effect. If thrown
            outside of a loop, a <code>BreakException</code> will cause the error below.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          A Break was triggered outside a loop.
        </p>
</dd>

      
      

      
<a name="ex_ReturnException"></a>
<dt>
          
<a name="idx_N156785"></a><code>ReturnException</code>
        
</dt>
<dd>
          
<p>
            This is not a standard TestException and cannot be caught by a <a href="control.html#step_CatchSequence" shape="rect">'Catch'</a>
            node. It is thrown by a <a href="procedures.html#step_ReturnStep" shape="rect">'Return'</a> node in order to return from a
            <a href="procedures.html#step_Procedure" shape="rect">'Procedure'</a>. From a script, raising a <code>ReturnException</code> will have the
            same effect. If thrown outside of a 'Procedure', a <code>ReturnException</code> will cause the
            error below.
          </p>
        
<p>
<b>Base class: </b><a href="#ex_TestException" shape="rect"><code>TestException</code></a>
</p>
<p>
<b>Message: </b>
          A Return was triggered outside a procedure.
        </p>
</dd>

      

      

      
<a name="ex_TestOutOfMemoryException"></a>
<dt>
          
<a name="idx_N156844"></a><code>TestOutOfMemoryException</code>
        
</dt>
<dd>
          
<p>
            This is a special exception that is thrown when QF-Test determines that it is running out
            of memory during test execution. The exception causes the test to abort immediately
            and cannot be caught because once QF-Test has run out of memory there is little it can do
            to handle it. QF-Test tries to keep a little reserve memory so it will at least try to
            save the run-log.
          </p>
        
</dd>

      

    
</dl>
  
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="navifooter">
<tr>
<td class="margin"></td><td class="navicon"><a href="manual.html"><img src="../icons/linktop.png" width="34" height="36" border="0" alt="Top" title="Top"></a></td><td class="navicon"><a href="contents.html#table-of-contents"><img src="../icons/linktoc.png" width="34" height="36" border="0" alt="Table of contents" title="Table of contents"></a></td><td class="navicon"><a href="nodes.html#sec_suite"><img src="../icons/linkprev.png" width="34" height="36" border="0" alt="Previous Chapter: 38&nbsp;Elements of a test-suite" title="Previous Chapter: 38&nbsp;Elements of a test-suite"></a></td><td class="navicon"><a href="technical.html#sec_technical"><img src="../icons/linkcont.png" width="34" height="36" border="0" alt="Next Page: IV&nbsp;Technical reference" title="Next Page: IV&nbsp;Technical reference"></a></td><td class="navicon"><img src="../icons/linknextdis.png" width="34" height="36" alt="" border="0"></td><td class="navicon"><a href="reference.html#sec_reference"><img src="../icons/linkup.png" width="34" height="36" border="0" alt="Chapter Overview: III&nbsp;Reference manual" title="Chapter Overview: III&nbsp;Reference manual"></a></td><td class="navicon"><a href="../../manual_en.pdf" target="_parent"><img src="../icons/linkpdf.png" width="34" height="36" border="0" alt="PDF version" title="PDF version"></a></td><td class="navcopymod">Last update: 9/6/2022<br>Copyright &copy; 1999-2022 Quality First Software GmbH</td>
</tr>
</table>
</body>
</html>
